# Generated by Django 6.0.2 on 2026-03-25 13:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('custom', '0001_initial'),
        ('rir', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('asset_code', models.CharField(editable=False, max_length=30, unique=True)),
                ('barcode', models.CharField(max_length=50, unique=True)),
                ('serial_number', models.CharField(blank=True, max_length=100, null=True)),
                ('purchase_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('DAMAGED', 'Damaged'), ('DISPOSED', 'Disposed')], default='ACTIVE', max_length=20)),
                ('is_distributed', models.BooleanField(default=False)),
                ('distributed_at', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('current_condition', models.CharField(choices=[('good', 'Good'), ('damaged', 'Damaged'), ('repair', 'Under Repair')], default='good', max_length=20)),
                ('hashed', models.CharField(blank=True, max_length=128)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='custom.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custom.category')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custom.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='custom.location')),
                ('model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='custom.model')),
                ('rir_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='rir.riritem')),
                ('sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custom.subcategory')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
